# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2d714fa53a7d5560eeb09953af3a7a440c34a88ab2e8fa9ed1bd19bd50c3dabdbdee7c9c1cd987d3fe8339a514f55030b1090f5200f8e9c81e5637b158b761a

test:
  secret_key_base: 7927ac1c7bd62478b8aa9a39a8cfd4d215e914b4b824c43771ae221326cb56a0e04ffc2f221d6d72253b09093970022fbe33e42337039379636719aa923bfc36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
